language: java
jdk:
  - oraclejdk8
# remove line "dist: trusty" and fast forward to xenial once oraclejdk8 is no longer required due to old JavaFX
dist: trusty
script:
  - "./build.sh"
cache:
  directories:
    - "$HOME/.m2"
